name: The Sorting Hat
version: 1.1
description: Assign groups and roles to users upon registration.
url: https://github.com/LionsMouthDigital/Statamic-Sorting-Hat
developer: Curtis Blackwell
developer_url: lionsmouth.digital
